apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-discovery-scaledobject
  namespace: data-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-discovery
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 15
  cooldownPeriod: 120
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"
    - type: rabbitmq
      metadata:
        host: amqp://guest:guest@rabbitmq.messaging.svc.cluster.local:5672/
        queueName: api-discovery-jobs
        queueLength: "10"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-validator-scaledobject
  namespace: data-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-validator
  minReplicaCount: 1
  maxReplicaCount: 6
  pollingInterval: 15
  cooldownPeriod: 120
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"
    - type: rabbitmq
      metadata:
        host: amqp://guest:guest@rabbitmq.messaging.svc.cluster.local:5672/
        queueName: api-validator-jobs
        queueLength: "10"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-enricher-scaledobject
  namespace: data-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-enricher
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 15
  cooldownPeriod: 120
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"
    - type: rabbitmq
      metadata:
        host: amqp://guest:guest@rabbitmq.messaging.svc.cluster.local:5672/
        queueName: api-enrichment-jobs
        queueLength: "5"
